[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; micro-ROS für PlatformIO (offizielle PIO-Variante)
lib_deps =
  https://github.com/micro-ROS/micro_ros_platformio

; ROS 2 Distro wählen: humble | jazzy | kilted (Default) | rolling
board_microros_distro = humble

; Transport wählen: serial | wifi | ethernet | wifi_nina | native_ethernet | custom
board_microros_transport = wifi

; Optional, aber hilfreich bei verschachtelten Includes
lib_ldf_mode = deep+

; Wenn du größere Sketches planst, kann das bleiben:
board_build.partitions = default.csv
