syntax = "proto3";

import "nanopb.proto";

message ToEsp32 {
  oneof command {
    AliveCommand alive = 1;
    GetDataCommand get_data = 2;
    SetMuxCommand set_mux = 3;
  }
}

message FromEsp32 {
  uint32 timestamp = 1;
  oneof response {
    Ack ack = 2;
    SensorSample sample = 3;
    Error error = 4;
    Debug debug = 5;
  }
}

message AliveCommand {
}

message GetDataCommand {
}

message SetMuxCommand {
  bool toggle = 1;
}

message Ack {
  string message = 1 [(nanopb).max_size = 64];
}

message SensorSample {
  uint32 sensor_id = 1;
  float value = 2;
  uint32 checksum = 3;
}

message Error {
  string error = 1 [(nanopb).max_size = 64];
}

message Debug {
  string text = 1 [(nanopb).max_size = 128];
}
