/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "messages_nanopb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SystemSettings, SystemSettings, AUTO)


PB_BIND(Ping, Ping, AUTO)


PB_BIND(GetSettings, GetSettings, AUTO)


PB_BIND(SetSettings, SetSettings, AUTO)


PB_BIND(SetMux, SetMux, AUTO)


PB_BIND(ToEsp32, ToEsp32, AUTO)


PB_BIND(Ack, Ack, AUTO)


PB_BIND(Error, Error, AUTO)


PB_BIND(Debug, Debug, AUTO)


PB_BIND(SettingsState, SettingsState, AUTO)


PB_BIND(SensorSample, SensorSample, AUTO)


PB_BIND(FromEsp32, FromEsp32, AUTO)



