/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MESSAGES_NANOPB_PB_H_INCLUDED
#define PB_MESSAGES_NANOPB_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _AliveCommand {
    char dummy_field;
} AliveCommand;

typedef struct _GetDataCommand {
    char dummy_field;
} GetDataCommand;

typedef struct _SetMuxCommand {
    bool toggle;
} SetMuxCommand;

typedef struct _ToEsp32 {
    pb_size_t which_command;
    union _ToEsp32_command {
        AliveCommand alive;
        GetDataCommand get_data;
        SetMuxCommand set_mux;
    } command;
} ToEsp32;

typedef struct _Ack {
    char message[64];
} Ack;

typedef struct _SensorSample {
    uint32_t sensor_id;
    float value;
    uint32_t checksum;
} SensorSample;

typedef struct _Error {
    char error[64];
} Error;

typedef struct _Debug {
    char text[128];
} Debug;

typedef struct _FromEsp32 {
    uint32_t timestamp;
    pb_size_t which_response;
    union _FromEsp32_response {
        Ack ack;
        SensorSample sample;
        Error error;
        Debug debug;
    } response;
} FromEsp32;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ToEsp32_init_default                     {0, {AliveCommand_init_default}}
#define FromEsp32_init_default                   {0, 0, {Ack_init_default}}
#define AliveCommand_init_default                {0}
#define GetDataCommand_init_default              {0}
#define SetMuxCommand_init_default               {0}
#define Ack_init_default                         {""}
#define SensorSample_init_default                {0, 0, 0}
#define Error_init_default                       {""}
#define Debug_init_default                       {""}
#define ToEsp32_init_zero                        {0, {AliveCommand_init_zero}}
#define FromEsp32_init_zero                      {0, 0, {Ack_init_zero}}
#define AliveCommand_init_zero                   {0}
#define GetDataCommand_init_zero                 {0}
#define SetMuxCommand_init_zero                  {0}
#define Ack_init_zero                            {""}
#define SensorSample_init_zero                   {0, 0, 0}
#define Error_init_zero                          {""}
#define Debug_init_zero                          {""}

/* Field tags (for use in manual encoding/decoding) */
#define SetMuxCommand_toggle_tag                 1
#define ToEsp32_alive_tag                        1
#define ToEsp32_get_data_tag                     2
#define ToEsp32_set_mux_tag                      3
#define Ack_message_tag                          1
#define SensorSample_sensor_id_tag               1
#define SensorSample_value_tag                   2
#define SensorSample_checksum_tag                3
#define Error_error_tag                          1
#define Debug_text_tag                           1
#define FromEsp32_timestamp_tag                  1
#define FromEsp32_ack_tag                        2
#define FromEsp32_sample_tag                     3
#define FromEsp32_error_tag                      4
#define FromEsp32_debug_tag                      5

/* Struct field encoding specification for nanopb */
#define ToEsp32_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,alive,command.alive),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,get_data,command.get_data),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (command,set_mux,command.set_mux),   3)
#define ToEsp32_CALLBACK NULL
#define ToEsp32_DEFAULT NULL
#define ToEsp32_command_alive_MSGTYPE AliveCommand
#define ToEsp32_command_get_data_MSGTYPE GetDataCommand
#define ToEsp32_command_set_mux_MSGTYPE SetMuxCommand

#define FromEsp32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp,         1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,ack,response.ack),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,sample,response.sample),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,error,response.error),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (response,debug,response.debug),   5)
#define FromEsp32_CALLBACK NULL
#define FromEsp32_DEFAULT NULL
#define FromEsp32_response_ack_MSGTYPE Ack
#define FromEsp32_response_sample_MSGTYPE SensorSample
#define FromEsp32_response_error_MSGTYPE Error
#define FromEsp32_response_debug_MSGTYPE Debug

#define AliveCommand_FIELDLIST(X, a) \

#define AliveCommand_CALLBACK NULL
#define AliveCommand_DEFAULT NULL

#define GetDataCommand_FIELDLIST(X, a) \

#define GetDataCommand_CALLBACK NULL
#define GetDataCommand_DEFAULT NULL

#define SetMuxCommand_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     toggle,            1)
#define SetMuxCommand_CALLBACK NULL
#define SetMuxCommand_DEFAULT NULL

#define Ack_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define Ack_CALLBACK NULL
#define Ack_DEFAULT NULL

#define SensorSample_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   sensor_id,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2) \
X(a, STATIC,   SINGULAR, UINT32,   checksum,          3)
#define SensorSample_CALLBACK NULL
#define SensorSample_DEFAULT NULL

#define Error_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   error,             1)
#define Error_CALLBACK NULL
#define Error_DEFAULT NULL

#define Debug_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   text,              1)
#define Debug_CALLBACK NULL
#define Debug_DEFAULT NULL

extern const pb_msgdesc_t ToEsp32_msg;
extern const pb_msgdesc_t FromEsp32_msg;
extern const pb_msgdesc_t AliveCommand_msg;
extern const pb_msgdesc_t GetDataCommand_msg;
extern const pb_msgdesc_t SetMuxCommand_msg;
extern const pb_msgdesc_t Ack_msg;
extern const pb_msgdesc_t SensorSample_msg;
extern const pb_msgdesc_t Error_msg;
extern const pb_msgdesc_t Debug_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ToEsp32_fields &ToEsp32_msg
#define FromEsp32_fields &FromEsp32_msg
#define AliveCommand_fields &AliveCommand_msg
#define GetDataCommand_fields &GetDataCommand_msg
#define SetMuxCommand_fields &SetMuxCommand_msg
#define Ack_fields &Ack_msg
#define SensorSample_fields &SensorSample_msg
#define Error_fields &Error_msg
#define Debug_fields &Debug_msg

/* Maximum encoded size of messages (where known) */
#define Ack_size                                 65
#define AliveCommand_size                        0
#define Debug_size                               130
#define Error_size                               65
#define FromEsp32_size                           139
#define GetDataCommand_size                      0
#define MESSAGES_NANOPB_PB_H_MAX_SIZE            FromEsp32_size
#define SensorSample_size                        17
#define SetMuxCommand_size                       2
#define ToEsp32_size                             4

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
