/* Automatically generated nanopb header */
/* Generated by nanopb-1.0.0-dev */

#ifndef PB_MESSAGES_NANOPB_PB_H_INCLUDED
#define PB_MESSAGES_NANOPB_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _ToEsp32 {
    uint64_t timestamp;
    char command[32];
    char payload[64];
    uint32_t hash;
} ToEsp32;

typedef struct _FromEsp32 {
    uint64_t timestamp;
    float temperature;
    float humidity;
    char status[32];
    uint32_t hash;
} FromEsp32;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define ToEsp32_init_default                     {0, "", "", 0}
#define FromEsp32_init_default                   {0, 0, 0, "", 0}
#define ToEsp32_init_zero                        {0, "", "", 0}
#define FromEsp32_init_zero                      {0, 0, 0, "", 0}

/* Field tags (for use in manual encoding/decoding) */
#define ToEsp32_timestamp_tag                    1
#define ToEsp32_command_tag                      2
#define ToEsp32_payload_tag                      3
#define ToEsp32_hash_tag                         4
#define FromEsp32_timestamp_tag                  1
#define FromEsp32_temperature_tag                2
#define FromEsp32_humidity_tag                   3
#define FromEsp32_status_tag                     4
#define FromEsp32_hash_tag                       5

/* Struct field encoding specification for nanopb */
#define ToEsp32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, STATIC,   SINGULAR, STRING,   command,           2) \
X(a, STATIC,   SINGULAR, STRING,   payload,           3) \
X(a, STATIC,   SINGULAR, UINT32,   hash,              4)
#define ToEsp32_CALLBACK NULL
#define ToEsp32_DEFAULT NULL

#define FromEsp32_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,         1) \
X(a, STATIC,   SINGULAR, FLOAT,    temperature,       2) \
X(a, STATIC,   SINGULAR, FLOAT,    humidity,          3) \
X(a, STATIC,   SINGULAR, STRING,   status,            4) \
X(a, STATIC,   SINGULAR, UINT32,   hash,              5)
#define FromEsp32_CALLBACK NULL
#define FromEsp32_DEFAULT NULL

extern const pb_msgdesc_t ToEsp32_msg;
extern const pb_msgdesc_t FromEsp32_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define ToEsp32_fields &ToEsp32_msg
#define FromEsp32_fields &FromEsp32_msg

/* Maximum encoded size of messages (where known) */
#define FromEsp32_size                           60
#define MESSAGES_NANOPB_PB_H_MAX_SIZE            ToEsp32_size
#define ToEsp32_size                             115

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
