/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-1.0.0-dev */

#include "messages_nanopb.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(SensorSample, SensorSample, AUTO)


PB_BIND(StatusMessage, StatusMessage, AUTO)


PB_BIND(CommandRequestStatus, CommandRequestStatus, AUTO)


PB_BIND(CommandSetPwm, CommandSetPwm, AUTO)


PB_BIND(CommandControlOutput, CommandControlOutput, AUTO)


PB_BIND(CommandSetConfig, CommandSetConfig, AUTO)


PB_BIND(ResponseAck, ResponseAck, AUTO)


PB_BIND(ResponseError, ResponseError, AUTO)


PB_BIND(ToEsp32, ToEsp32, 2)


PB_BIND(FromEsp32, FromEsp32, 2)



