# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
# Protobuf Python Version: 4.25.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import nanopb_pb2 as nanopb__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0emessages.proto\x1a\x0cnanopb.proto\"Z\n\x07ToEsp32\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x16\n\x07\x63ommand\x18\x02 \x01(\tB\x05\x92?\x02\x08 \x12\x16\n\x07payload\x18\x03 \x01(\tB\x05\x92?\x02\x08@\x12\x0c\n\x04hash\x18\x04 \x01(\r\"j\n\tFromEsp32\x12\x11\n\ttimestamp\x18\x01 \x01(\x04\x12\x13\n\x0btemperature\x18\x02 \x01(\x02\x12\x10\n\x08humidity\x18\x03 \x01(\x02\x12\x15\n\x06status\x18\x04 \x01(\tB\x05\x92?\x02\x08 \x12\x0c\n\x04hash\x18\x05 \x01(\rb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'messages_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_TOESP32'].fields_by_name['command']._options = None
  _globals['_TOESP32'].fields_by_name['command']._serialized_options = b'\222?\002\010 '
  _globals['_TOESP32'].fields_by_name['payload']._options = None
  _globals['_TOESP32'].fields_by_name['payload']._serialized_options = b'\222?\002\010@'
  _globals['_FROMESP32'].fields_by_name['status']._options = None
  _globals['_FROMESP32'].fields_by_name['status']._serialized_options = b'\222?\002\010 '
  _globals['_TOESP32']._serialized_start=32
  _globals['_TOESP32']._serialized_end=122
  _globals['_FROMESP32']._serialized_start=124
  _globals['_FROMESP32']._serialized_end=230
# @@protoc_insertion_point(module_scope)
