services:
  ros2_agent:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - ../.env
    environment:
      - ROS_DOMAIN_ID=${ROS_DOMAIN_ID}
      - SERIAL_DEV=${SERIAL_DEV}
      - AGENT_VERBOSITY=${AGENT_VERBOSITY}
    devices:
      - "${SERIAL_DEV}:${SERIAL_DEV}"
    group_add:
      - dialout
    network_mode: host
    restart: unless-stopped
    tty: true
    stdin_open: true
