
services:
  microros-agent:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    env_file:
      - ../.env
    ports:
      - "${AGENT_PORT:-8888}:${AGENT_PORT:-8888}/udp"
    restart: unless-stopped
    privileged: true
    tty: true
    stdin_open: true