[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; micro-ROS für PlatformIO direkt aus GitHub
lib_deps =
  https://github.com/micro-ROS/micro_ros_platformio

; PIO baut micro-ROS selbst, gesteuert über diese zwei Zeilen:
board_microros_distro = humble     ; alternativ: kilted / jazzy / rolling
board_microros_transport = serial  ; USB-Serial zum Agent

; Kleines Helferchen für verschachtelte Includes
lib_ldf_mode = chain+
