version: "3.9"

services:
  protobuf:
    build: .
    volumes:
      - ./protobuf_msgs:/rig/protobuf_msgs:ro
      - ./protobuf_generated:/rig/protobuf_generated
      - ./workspace:/rig/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
