version: "3.9"

services:
  protobuf:
    build: .
    volumes:
    #  - ./workspace/protobuf_msgs:/workspace/protobuf_msgs:ro
      - ./workspace:/workspace
    working_dir: /workspace
    stdin_open: true
    tty: true
