version: "3.9"

services:
  protobuf:
    build: .
    volumes:
      - ./protos:/workspace/protobuf_msgs
      - ./output:/workspace/protobuf_gnerated
      - ./workspace:/workspace/workspace

    command: ["python", "generate.py"]
